# Generated by Django 2.2 on 2019-04-30 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottleAnalytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottlereading',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
