# Generated by Django 2.2 on 2019-04-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottleAnalytics', '0002_bottlereading_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('weight', models.FloatField(default=65)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
