# Generated by Django 2.2 on 2019-04-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottleAnalytics', '0003_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='weight',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='activity_level',
            field=models.CharField(choices=[('SE', 'Sedentary'), ('LA', 'Low Active'), ('AC', 'Active'), ('VA', 'Very Active')], default='LA', max_length=2),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
