# Generated by Django 2.2 on 2019-05-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottleAnalytics', '0005_previousscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottlereading',
            name='temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bottlereading',
            name='weight',
            field=models.FloatField(),
        ),
    ]
