# Generated by Django 2.2 on 2019-05-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottleAnalytics', '0006_auto_20190503_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousscore',
            name='consumption',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='previousscore',
            name='ideal_consumption',
            field=models.FloatField(default=0.0),
        ),
    ]
